# Generated by Django 5.2.5 on 2025-08-13 12:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("structure", models.CharField(blank=True, max_length=255)),
                ("theme", models.CharField(blank=True, max_length=255)),
                ("zone", models.CharField(blank=True, max_length=255)),
                ("ligne_source", models.CharField(blank=True, max_length=255)),
                ("equipement", models.CharField(blank=True, max_length=255)),
                ("anomalie", models.TextField(blank=True)),
                ("action_a_mener", models.TextField(blank=True)),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("BASSE", "Basse"),
                            ("MOYENNE", "Moyenne"),
                            ("HAUTE", "Haute"),
                            ("CRITIQUE", "Critique"),
                        ],
                        default="MOYENNE",
                        max_length=16,
                    ),
                ),
                (
                    "budget_dzd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("delais", models.DateField(blank=True, null=True)),
                ("date_realisation", models.DateField(blank=True, null=True)),
                ("pdca_p", models.DateTimeField(blank=True, null=True)),
                ("pdca_d", models.DateTimeField(blank=True, null=True)),
                ("pdca_c", models.DateTimeField(blank=True, null=True)),
                ("pdca_a", models.DateTimeField(blank=True, null=True)),
                ("evaluation_delais", models.DateField(blank=True, null=True)),
                (
                    "evaluation_efficacite",
                    models.CharField(
                        choices=[
                            ("VIDE", "—"),
                            ("EFFICACE", "Efficace"),
                            ("PARTIELLE", "Partielle"),
                            ("INEFFICACE", "Inefficace"),
                        ],
                        default="VIDE",
                        max_length=16,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_COURS", "En cours"),
                            ("EN_TRAITEMENT", "En traitement"),
                            ("CLOTUREE", "Clôturée"),
                            ("ARCHIVEE", "Archivée"),
                            ("REJETEE", "Rejetée"),
                        ],
                        default="EN_COURS",
                        max_length=16,
                    ),
                ),
                ("j_delta", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_filles",
                        to="paa.action",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsables",
                    models.ManyToManyField(
                        blank=True,
                        related_name="actions_responsable",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255, unique=True)),
                (
                    "lien_source",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "mode_stockage",
                    models.CharField(
                        choices=[
                            ("EXCEL", "Excel externe"),
                            ("INTERNE", "Stockage interne"),
                        ],
                        default="EXCEL",
                        max_length=16,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pilote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plans_pilotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("nom",),
            },
        ),
        migrations.CreateModel(
            name="ActionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priorite_locale",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BASSE", "Basse"),
                            ("MOYENNE", "Moyenne"),
                            ("HAUTE", "Haute"),
                            ("CRITIQUE", "Critique"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="paa.action"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="paa.plan",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(fields=["code"], name="paa_action_code_d21ffc_idx"),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(fields=["statut"], name="paa_action_statut_e87f9f_idx"),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["priorite"], name="paa_action_priorit_a2ff24_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="actionplan",
            unique_together={("action", "plan")},
        ),
    ]
